/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "var(--canvas)",
        surface: {
          DEFAULT: "var(--surface)",
          muted: "var(--surface-muted)",
          raised: "var(--surface-raised)",
        },
        saffron: {
          DEFAULT: "var(--saffron)",
          hover: "var(--saffron-hover)",
          muted: "var(--saffron-muted)",
          soft: "var(--saffron-soft)",
        },
        emerald: {
          DEFAULT: "var(--emerald)",
          muted: "var(--emerald-muted)",
          soft: "var(--emerald-soft)",
        },
        ruby: {
          DEFAULT: "var(--ruby)",
          muted: "var(--ruby-muted)",
          soft: "var(--ruby-soft)",
        },
        ink: {
          DEFAULT: "var(--ink)",
          secondary: "var(--ink-secondary)",
          muted: "var(--ink-muted)",
          "on-accent": "var(--ink-on-accent)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
        },
        focus: "var(--focus-ring)",
        jewel: {
          50: "var(--jewel-50)",
          100: "var(--jewel-100)",
          200: "var(--jewel-200)",
          300: "var(--jewel-300)",
          400: "var(--jewel-400)",
          500: "var(--jewel-500)",
          600: "var(--jewel-600)",
          700: "var(--jewel-700)",
          800: "var(--jewel-800)",
          900: "var(--jewel-900)",
          950: "var(--jewel-950)",
          gold: "var(--jewel-gold)",
          goldLight: "var(--jewel-gold-light)",
          emerald: "var(--jewel-emerald)",
          saffron: "var(--jewel-saffron)",
          ruby: "var(--jewel-ruby)",
        },
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        sans: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        caption: ["0.75rem", { lineHeight: "1rem" }],
        body: ["0.875rem", { lineHeight: "1.25rem" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem" }],
        "heading-sm": ["1.125rem", { lineHeight: "1.75rem" }],
        heading: ["1.25rem", { lineHeight: "1.75rem" }],
        "heading-md": ["1.5rem", { lineHeight: "2rem" }],
        "heading-lg": ["1.875rem", { lineHeight: "2.25rem" }],
        display: ["2.25rem", { lineHeight: "2.5rem" }],
        "display-lg": ["3rem", { lineHeight: "3.5rem" }],
        "display-xl": ["4rem", { lineHeight: "4.5rem" }],
      },
      spacing: {
        1: "0.25rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
      },
      borderRadius: {
        pill: "9999px",
        sm: "0.5rem",
        DEFAULT: "0.75rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      boxShadow: {
        subtle: "0 1px 2px 0 rgb(0 0 0 / 0.03)",
        soft: "0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.03)",
        medium: "0 10px 15px -3px rgb(0 0 0 / 0.06), 0 4px 6px -4px rgb(0 0 0 / 0.03)",
        elevated: "0 20px 25px -5px rgb(0 0 0 / 0.06), 0 8px 10px -6px rgb(0 0 0 / 0.03)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-up": "slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-down": "slideDown 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
        "spin-slow": "spin 2s linear infinite",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "200ms",
        slow: "300ms",
      },
      backgroundImage: {
        "saffron-gradient": "linear-gradient(135deg, var(--saffron) 0%, var(--ink) 100%)",
        "saffron-radial": "radial-gradient(circle at center, var(--saffron-muted) 0%, transparent 70%)",
      },
    },
  },
  plugins: [],
};