/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: "var(--surface)",
          muted: "var(--surface-muted)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          muted: "var(--accent-muted)",
        },
        jewel: {
          50: "var(--jewel-50)",
          100: "var(--jewel-100)",
          200: "var(--jewel-200)",
          300: "var(--jewel-300)",
          400: "var(--jewel-400)",
          500: "var(--jewel-500)",
          600: "var(--jewel-600)",
          700: "var(--jewel-700)",
          800: "var(--jewel-800)",
          900: "var(--jewel-900)",
          950: "var(--jewel-950)",
          gold: "var(--jewel-gold)",
          goldLight: "var(--jewel-gold-light)",
          emerald: "var(--jewel-emerald)",
          saffron: "var(--jewel-saffron)",
          ruby: "var(--jewel-ruby)",
        },
        border: "var(--border)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-on-accent": "var(--text-on-accent)",
        "jewel-deep": "var(--text-primary)",
        emerald: "var(--emerald)",
        saffron: "var(--saffron)",
        ruby: "var(--ruby)",
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        sans: ["var(--font-body)", "sans-serif"],
      },
      fontSize: {
        caption: ["var(--text-xs)", { lineHeight: "1rem" }],
        body: ["var(--text-sm)", { lineHeight: "1.25rem" }],
        "body-lg": ["var(--text-base)", { lineHeight: "1.5rem" }],
        "heading-sm": ["var(--text-lg)", { lineHeight: "1.75rem" }],
        heading: ["var(--text-xl)", { lineHeight: "1.75rem" }],
        "heading-md": ["var(--text-2xl)", { lineHeight: "2rem" }],
        "heading-lg": ["var(--text-3xl)", { lineHeight: "2.25rem" }],
        display: ["var(--text-4xl)", { lineHeight: "2.5rem" }],
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        subtle: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        soft: "0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
        medium: "0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.04)",
        elevated: "0 20px 25px -5px rgb(0 0 0 / 0.08), 0 8px 10px -6px rgb(0 0 0 / 0.04)",
        jewel: "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
        "jewel-lg": "0 4px 12px -2px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.04)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-up": "slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
        "spin-slow": "spin 2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "200ms",
        slow: "300ms",
      },
    },
  },
  plugins: [],
};
