server {
    listen 80;

    resolver 127.0.0.11 valid=30s ipv6=off;

    location /api/ {
        set $upstream_be http://be:3001;
        proxy_pass $upstream_be;
        proxy_http_version 1.1;
    }

    location /socket.io/ {
        set $upstream_ws http://ws:3002;
        proxy_pass $upstream_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location / {
        set $upstream_web http://web:3000;
        proxy_pass $upstream_web;
        proxy_http_version 1.1;
    }
}
